### ISSUE TITLE
fakecheer triggers everything up to the amount specified

### ISSUE THREAD

**Issue by darkphan** [ThatGamerBlue/pay2spawn-reborn#5]
While testing things I noticed that the fakecheer command triggers everything up to the amount specified in the fakecheer. I have not tested if the same happens for real cheers, but this could be bad, lol.

**Comment by ThatGamerBlue** [comment]
Working as intended.

**Comment by darkphan** [comment]
That makes no sense. If I had a 100 and a 200 reward set up, and someone cheers 200 it should only do the 200.
